######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 13 23:53:46 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gameview.h
SOURCES += GameView.cpp main.cpp
RESOURCES += list.qrc
